// File generated by Antigravity to fix Firebase Web initialization.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW4uyCg59BoKtmRkXj_HCFP8LRbvTiG2E',
    appId: '1:471475305910:web:dummy_id_for_fix', // Replace with real Web App ID if needed
    messagingSenderId: '471475305910',
    projectId: 'finance-dccfa',
    authDomain: 'finance-dccfa.firebaseapp.com',
    storageBucket: 'finance-dccfa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW4uyCg59BoKtmRkXj_HCFP8LRbvTiG2E',
    appId: '1:471475305910:android:b6c7e689eb49f1847d9517',
    messagingSenderId: '471475305910',
    projectId: 'finance-dccfa',
    storageBucket: 'finance-dccfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4uyCg59BoKtmRkXj_HCFP8LRbvTiG2E',
    appId: '1:471475305910:ios:dummy_id_for_fix',
    messagingSenderId: '471475305910',
    projectId: 'finance-dccfa',
    storageBucket: 'finance-dccfa.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );
}
